apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: monitor-project
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/jordan/k8s-monitor
    targetRevision: main
    path: environments/prod/charts/grafana
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true