apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitor-project
  namespace: argocd
spec:
  description: Management project
  sourceRepos:
    - "http://gitea-http.gitea.svc.cluster.local:3000/jordan/k8s-monitor"
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  syncWindows: []
  orphanedResources:
    warn: true