apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
type: Opaque
data:
  # This is "admin:admin" - change this to a better password
  # You can generate this with: echo -n "admin:$(openssl passwd -apr1 YOUR_PASSWORD)" | base64
  auth: ${BASE64_ENCODED_AUTH}