apiVersion: v1
kind: ServiceAccount
metadata:
  name: beszel-init-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: beszel-init-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: beszel-init-rolebinding
subjects:
- kind: ServiceAccount
  name: beszel-init-sa
roleRef:
  kind: Role
  name: beszel-init-role
  apiGroup: rbac.authorization.k8s.io