apiVersion: v1
kind: ConfigMap
metadata:
  name: beszel-kubeconfig
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: default
      cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kubernetes.default.svc
    contexts:
    - name: default
      context:
        cluster: default
        namespace: monitoring
        user: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    current-context: default